repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
      - id: black
        args: [--line-length=120]

  - repo: https://github.com/kumaraditya303/mirrors-pyright
    rev: v1.1.210
    hooks:
      - id: pyright

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8